Description: >
  This template contains the DynamoDB table required by our entire stack.
  We create it in a separate nested template, so they can be referenced
  by all of the other nested templates.

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  VPC:
    Description: Choose which VPC this ECS cluster should be deployed to
    Type: AWS::EC2::VPC::Id

Resources:

  ContactRequestsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "N"
        - AttributeName: "creation_timestamp"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "creation_timestamp"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "3"
        WriteCapacityUnits: "3"
      TableName: "Contact-Requests"

Outputs:

  ContactRequestsTable:
    Description: A reference to the DynamoDB table Contact-Requests
    Value: !Ref ContactRequestsTable