name: Build and Deploy Backend

on:
  workflow_dispatch: {}

env:
  applicationfolder: server-backend
  AWS_REGION: us-east-1
  S3BUCKET: michael-portfolio-us-east-1
  CFN_STACK: michael-portfolio


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        working-directory: ${{ env.applicationfolder }}
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: michael-portfolio-backend
        run: |
          docker build -t $REGISTRY/$REPOSITORY .
          docker push $REGISTRY/$REPOSITORY
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Deploy Cloudformation
      run: |
        echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
        aws s3 cp aws/cloudformation s3://${{ env.S3BUCKET }}/ --recursive
        aws cloudformation update-stack --stack-name ${{ env.CFN_STACK }} --template-url https://${{ env.S3BUCKET }}.s3.amazonaws.com/master.yaml
