name: Build and Deploy

on:
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  S3BUCKET: michael-portfolio-us-east-1
  CFN_STACK: michael-portfolio


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: michael-portfolio-backend
        run: |
          version=`git rev-parse HEAD`
          docker build -t $REGISTRY/$REPOSITORY:$version .
          docker push $REGISTRY/$REPOSITORY:$version
          
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Deploy Cloudformation
      run: |
        echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
        commit_hash=`git rev-parse HEAD`
        aws s3 cp aws/cloudformation s3://${{ env.S3BUCKET }}/ --recursive
        aws cloudformation deploy --stack-name ${{ env.CFN_STACK }} --template-file aws/cloudformation/master.yaml \
          --parameter-overrides "GitCommit=$commit_hash" --no-fail-on-empty-changeset \
          --capabilities CAPABILITY_NAMED_IAM CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
    - name: Cleanup Old ECR Images
      env:
        REPOSITORY: michael-portfolio-backend
      run: |
        hash=`git rev-parse HEAD`
        img_tags_delete=$(aws ecr list-images --repository-name ${{ env.REPOSITORY }} --output=text | grep -v $hash |  awk '{print "imageTag=" $3}' | xargs)
        aws ecr batch-delete-image --repository-name ${{ env.REPOSITORY }} --image-ids "$img_tags_delete"

